### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by lordcrekit** [lordcrekit/MI-449-SS17-740-css-sass-intro-8dVLYn#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://lordcrekit.github.io/MI-449-SS17-740-css-sass-intro-8dVLYn/) and meets the following criteria:

- [x] All components in [this HTML](https://gist.github.com/egillespie/15433761e640077f93660b4555a3d88b) are styled using Sass
- [x] Use four colors from a [random color palette](https://coolors.co/) (just copy the hex values into your Sass file) and link to your palette in the HTML
- [x] Font sizes are all determined by one base font size variable, even in `input` and `textarea` elements
- [x] All text uses the same font family, even in `input` and `textarea` elements
- [x] Elements shaped like a box (`img`, `input[type="text"]`, `textarea`) have the same `border-radius`
- [x] At least one built-in Sass function is used to style a component
- [x] Variables are defined in their own Sass file
- [x] Sass files are saved in a `source` directory and CSS files are saved in a `compiled` directory
- [x] A source map for your component library is included in the project

I didn't know what a component library was. So I just made a normal library!

**Comment by egillespie** [comment]
Hi @lordcrekit, do you mind putting the original HTML we provided back into your project and styling those elements?

The link on the project was intended to provide some insight into what a component library is, and the phrase "component library" can be taken quite literally. It's a library of components that a designer will create and style in such a way that a brand can be consistently presented on the web.

Typically a brand will have some basic stylistic aspects such as colors from a logo, font, curviness (or lack thereof), etc. that will be applied to a variety of elements. Those basic aspects make good variables to apply to a set of elements -- in this case the elements that we provided -- so any number of websites and other media can be created to present uniform portrayal of the brand.

You can pick whichever font, border radius, etc. that you want. We only ask that you pick four basic colors from one of the randomly generated palettes on Coolors.co.

Move our HTML back in and give it another shot. If you have any questions, feel free to hit me up here in the comments or in Slack! 💫

**Comment by lordcrekit** [comment]
What html you originally provided? Was it in one of the links?

**Comment by egillespie** [comment]
Yep, the first criteria has a link that says to style [this HTML](https://gist.github.com/egillespie/15433761e640077f93660b4555a3d88b). 😉

**Comment by lordcrekit** [comment]
Don't know how I missed that.. okay, here's attempt #2!

**Comment by egillespie** [comment]
This looks like what I was expecting! 😄  I like what you did with the colors you were given, especially with respect to the headings.

Here are a few things I noticed while looking over your code:

### `comperil*.sh`

I like what you did here. You'll see a Node-specific way to do stuff like this in an upcoming lesson. 😉 

### Text box border

Do you mind making the border of your `textarea` element look the same as your other textbox fields? Ditto with applying the border radius. Making similar-looking elements looks consistent is pretty important in a component library.

### Do something with tables

You're applying styles to your table that aren't noticeable (border radius on rows and header cells). Try applying a background color or something that would make your styles stand out.

### Prefix `vars.scss` with `_`

Sass files that don't produce their own CSS file should be prefixed with a `_` character. The reason for this is that depending on how you call `node-sass`, you may inadvertently generate more CSS files than you are including in your HTML. Sass files that being with `_` will never generate their own CSS file.

### `.gitignore`

Nice work! We'll provide tips for making a robust `.gitignore` file in an upcoming lesson too!

---

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! 🍰

**Comment by lordcrekit** [comment]
# Fixes!
- Renamed the vars file
- Added background to the table
- The text/password/and textarea border are identical.
Should have noticed the borders earlier. CURSE YOU CSS DEFAAAULTS!!!

# Extras!
- Moved all the stuff from sh files to proper npm scripts. I didn't want to wait to do the lesson :laughing:  
- Also the inputs glow when you hover over them!

**Comment by egillespie** [comment]
This looks great! The `package.json` looks pretty good too. In the next lesson we'll introduce you to some better tools to give you better ways to chain commands than `&&`, even though it's convenient when you don't want to introduce dependencies. :shipit:

**Comment by lordcrekit** [comment]
That sounds cool. I look forward to it!
